name: Build and Deploy

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install 🔧
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Artisan 🔮
        env:
          TZ: Europe/Moscow
          APP_ENV: production
        run: |
          php artisan rss:download
          php artisan rss:exchange
          php artisan rss:similar
          php artisan rss:page
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: public
